export enum Color {
  PRIMARY = "var(--color-primary)",
  PRIMARY_LIGHT = "var(--color-primary-light)",
  SECONDARY = "var(--color-secondary)",
  WHITE = "var(--color-white)",
  GREY = "var(--color-gray)",
  LIGHT = "var(--color-light)",
  RED = "var(--color-red)",
  BLUE = "var(--color-blue)",
  GREEN = "var(--color-green)",
  ORANGE = "var(--color-orange)",
  PURPLE = "var(--color-purple)",
  BACKGROUND = "var(--color-background)",
  BLACK = "var(--color-black)",
}
